version: '3.8' 

services:
  frontend:
    image: 103975337985.dkr.ecr.us-east-2.amazonaws.com/deploysphere-frontend:v1.0.1

    ports:
      - "80:80"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://18.224.69.172:8000/api/

  backend:
    image: 103975337985.dkr.ecr.us-east-2.amazonaws.com/deploysphere-backend:v1.0.1

    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db 
      MYSQL_PORT: 3306
      DJANGO_SECRET_KEY: "m%t7h7@st+=k0o23s)ao!gz+h48#zp-^8bzrl#*4s1o5uzs6=j"
      DJANGO_ALLOWED_HOSTS: "18.224.69.172,backend, localhost, 127.0.0.1" 
      DJANGO_DEBUG: "False" 

    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Root password for MySQL
      MYSQL_DATABASE: mydatabase        # Database name to create
      MYSQL_USER: user                  # User for the database
      MYSQL_PASSWORD: password          # Password for the user
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: